-- ============================================================
-- DaVinci Music
-- Base de datos inicial
-- Tabla: CATEGORIA_INSTRUMENTO
-- ============================================================

CREATE TABLE categoria_instrumento (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),

    CONSTRAINT pk_categoria_instrumento
        PRIMARY KEY (id_categoria),

    CONSTRAINT uq_categoria_instrumento_nombre
        UNIQUE (nombre_categoria)
);